# Generated by Django 5.2.8 on 2026-05-10 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_start', models.DateField()),
                ('schedule_end', models.DateField()),
                ('payroll_start', models.DateField()),
                ('payroll_end', models.DateField()),
                ('pay_date', models.DateField(help_text='Expected paycheck disbursement date.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Payroll Cycle',
                'verbose_name_plural': 'Payroll Cycles',
                'ordering': ['-schedule_start'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduling.payrollcycle')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='employees.group')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'unique_together': {('cycle', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2')])),
                ('start_date', models.DateField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='scheduling.schedule')),
            ],
            options={
                'verbose_name': 'Week',
                'verbose_name_plural': 'Weeks',
                'ordering': ['week_number'],
                'unique_together': {('schedule', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_holiday', models.BooleanField(default=False, help_text='Flag this date as a public holiday.')),
                ('holiday_name', models.CharField(blank=True, help_text="Optional name shown on the schedule (e.g. 'Christmas Day').", max_length=100)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='scheduling.week')),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
                'ordering': ['date'],
                'unique_together': {('week', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('include_lunch', models.BooleanField(default=False, help_text='Deduct the default lunch duration from total scheduled hours.')),
                ('is_adhoc', models.BooleanField(default=False, help_text='True when this shift was added on the fly (not part of the original schedule). Ad-hoc shifts appear on the time-keeping board and count toward payroll but are visually distinguished on schedule views.')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='scheduling.day')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_shifts', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Scheduled Shift',
                'verbose_name_plural': 'Scheduled Shifts',
                'ordering': ['day__date', 'start_time'],
                'unique_together': {('employee', 'day')},
            },
        ),
    ]
