# Generated by Django 5.2.8 on 2026-05-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledshift',
            name='is_adhoc',
            field=models.BooleanField(default=False, help_text='True when this shift was added on the fly (not part of the original schedule). Ad-hoc shifts appear on the time-keeping board and count toward payroll but are visually distinguished on schedule views.'),
        ),
    ]
