# Generated by Django 5.2.8 on 2026-05-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_rate_multiplier', models.DecimalField(decimal_places=2, default='1.50', help_text='e.g. 1.5 for time-and-a-half.', max_digits=4)),
                ('holiday_rate_multiplier', models.DecimalField(decimal_places=2, default='2.00', help_text='e.g. 2.0 for double time on public holidays.', max_digits=4)),
                ('overtime_threshold_hours', models.DecimalField(decimal_places=2, default='40.00', help_text='Weekly hours above which the overtime rate applies.', max_digits=5)),
                ('deduction_percentage', models.DecimalField(decimal_places=2, default='0.00', help_text='Flat deduction percentage applied to gross pay (e.g. 10.00 for 10%).', max_digits=5)),
                ('default_lunch_duration_minutes', models.PositiveIntegerField(default=30, help_text="Minutes deducted from a shift when 'include lunch break' is checked.")),
                ('week_start_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6, help_text='Day that each schedule week begins on.')),
                ('schedule_cycle_start', models.DateField(blank=True, help_text='The Sunday (or configured week start) of the very first schedule cycle. All future cycles are calculated as 14-day multiples from this date.', null=True)),
                ('payroll_cycle_offset_days', models.IntegerField(default=3, help_text="Days before the schedule cycle start that the payroll cycle opens. Default 3 = the Thursday of the previous cycle's week 2.")),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
