# Generated by Django 5.2.8 on 2026-05-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='payroll_close_week',
            field=models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2')], default=2, help_text='Which week of the schedule cycle the close day falls in.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='payroll_close_weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=3, help_text='Day of the week on which payroll close-off is triggered.'),
        ),
    ]
