# Generated by Django 5.2.8 on 2026-05-10 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('lunch_start', models.TimeField(blank=True, null=True)),
                ('lunch_end', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('scheduled_shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actual_shift', to='scheduling.scheduledshift')),
            ],
            options={
                'verbose_name': 'Actual Shift',
                'verbose_name_plural': 'Actual Shifts',
            },
        ),
    ]
