# Generated by Django 5.2.8 on 2026-05-10 12:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_run', to='scheduling.payrollcycle')),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_rate_snapshot', models.DecimalField(decimal_places=2, max_digits=8)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll_close.payrollrun')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['employee__last_name', 'employee__first_name'],
                'unique_together': {('run', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('regular', 'Regular'), ('overtime', 'Overtime'), ('holiday', 'Holiday'), ('deduction', 'Deduction')], max_length=10)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll_close.payslip')),
            ],
            options={
                'verbose_name': 'Payslip Line',
                'verbose_name_plural': 'Payslip Lines',
                'ordering': ['date', 'line_type'],
            },
        ),
    ]
